
const livingdata = [
    {
        id: "装扮圣诞树",
        pic: "/images/living1.jpeg",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "吃麦芽糖",
        title: "我们的仪式感",
        pic: "/images/living2.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "一起zipline",
        title: "我们的仪式感",
        pic: "/images/living3.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, , 
    {
        id: "床前聊天分享",
        title: "我们的仪式感",
        pic: "/images/living4.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, , 
    {
        id: "Jelltcat娃娃",
        title: "我们的仪式感",
        pic: "/images/living5.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, , 
    {
        id: "满天星",
        title: "我们的仪式感",
        pic: "/images/living6.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "一起逛whole food",
        title: "我们的仪式感",
        pic: "/images/living8.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "小橙橙",
        title: "我们的仪式感",
        pic: "/images/living7.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "一起在target",
        title: "我们的仪式感",
        pic: "/images/living9.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "一起逛大华",
        title: "我们的仪式感",
        pic: "/images/living10.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "妹妹在画画",
        title: "我们的仪式感",
        pic: "/images/living11.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "一起逛街试衣服",
        title: "我们的仪式感",
        pic: "/images/living12.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "scooter",
        title: "我们的仪式感",
        pic: "/images/living13.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "阅读的妹妹",
        title: "我们的仪式感",
        pic: "/images/living14.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "这是哥哥",
        title: "我们的仪式感",
        pic: "/images/living15.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "蒸饭外卖",
        title: "我们的仪式感",
        pic: "/images/living16.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "妹妹收拾小家家",
        title: "我们的仪式感",
        pic: "/images/living17.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "疫情中的火锅",
        title: "我们的仪式感",
        pic: "/images/living18.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "一起煮凉茶",
        title: "我们的仪式感",
        pic: "/images/living19.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "新的手机包包",
        title: "我们的仪式感",
        pic: "/images/living20.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "认真记账过生活",
        title: "我们的仪式感",
        pic: "/images/living21.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "出租屋",
        title: "我们的仪式感",
        pic: "/images/living22.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "认真做饭饭",
        title: "我们的仪式感",
        pic: "/images/living23.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "妹妹的画画",
        title: "我们的仪式感",
        pic: "/images/living24.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "妹妹的新表情",
        title: "我们的仪式感",
        pic: "/images/living25.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "大肥猪和妹妹",
        title: "我们的仪式感",
        pic: "/images/living26.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "一起在唱歌",
        title: "我们的仪式感",
        pic: "/images/living27.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "静静在陪伴",
        title: "我们的仪式感",
        pic: "/images/living28.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "K歌",
        title: "我们的仪式感",
        pic: "/images/living29.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }, 
    {
        id: "wait a minute",
        title: "我们的仪式感",
        pic: "/images/living30.jpeg",
        alt: "我们的仪式感",
        blurb: "As a couple, we truly enjoy living together and making a home that is warm and welcoming. Every day, we work together to create a comfortable and harmonious environment, taking care of tasks such as cooking, cleaning, and decorating..",
    }
];

export default livingdata;